from __future__ import annotations

import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).parents[1]
CATALOG_PATH = ROOT / "data" / "seeds" / "anchors.v2.json"
MANIFEST_PATH = ROOT / "data" / "manifests" / "seed-catalog.v2.json"

SEEDS: dict[str, tuple[tuple[str, str], ...]] = {
    "people": (
        ("Q76", "Barack Obama"),
        ("Q8023", "Nelson Mandela"),
        ("Q1001", "Mahatma Gandhi"),
        ("Q8027", "Martin Luther King Jr."),
        ("Q41921", "Rosa Parks"),
        ("Q635", "Cleopatra"),
        ("Q1048", "Julius Caesar"),
        ("Q517", "Napoleon"),
        ("Q7226", "Joan of Arc"),
        ("Q37103", "Florence Nightingale"),
        ("Q102870", "Harriet Tubman"),
        ("Q32732", "Malala Yousafzai"),
        ("Q43033", "Desmond Tutu"),
        ("Q83396", "Eleanor Roosevelt"),
        ("Q8016", "Winston Churchill"),
        ("Q211519", "Emmeline Pankhurst"),
        ("Q215562", "Frederick Douglass"),
        ("Q4604", "Confucius"),
        ("Q11903", "Hypatia"),
        ("Q309333", "Mansa Musa"),
    ),
    "history_society": (
        ("Q362", "World War II"),
        ("Q361", "World War I"),
        ("Q6534", "French Revolution"),
        ("Q2269", "Industrial Revolution"),
        ("Q2277", "Roman Empire"),
        ("Q11768", "Ancient Egypt"),
        ("Q4692", "Renaissance"),
        ("Q12539", "Age of Enlightenment"),
        ("Q8683", "Cold War"),
        ("Q1065", "United Nations"),
        ("Q7174", "Democracy"),
        ("Q8458", "Human rights"),
        ("Q7252", "Feminism"),
        ("Q48537", "Civil rights movement"),
        ("Q169390", "Abolitionism"),
        ("Q11034", "Printing"),
        ("Q12519", "Magna Carta"),
        ("Q36288", "Silk Road"),
        ("Q42005", "Black Death"),
        ("Q5086", "Berlin Wall"),
    ),
    "science_technology": (
        ("Q937", "Albert Einstein"),
        ("Q7186", "Marie Curie"),
        ("Q7259", "Ada Lovelace"),
        ("Q7251", "Alan Turing"),
        ("Q11740", "Katherine Johnson"),
        ("Q935", "Isaac Newton"),
        ("Q307", "Galileo Galilei"),
        ("Q9036", "Nikola Tesla"),
        ("Q80", "Tim Berners-Lee"),
        ("Q413", "Physics"),
        ("Q333", "Astronomy"),
        ("Q7187", "Gene"),
        ("Q7430", "DNA"),
        ("Q9121", "Atom"),
        ("Q10693", "Periodic table"),
        ("Q944", "Quantum mechanics"),
        ("Q11452", "General relativity"),
        ("Q68", "Computer"),
        ("Q75", "Internet"),
        ("Q4213", "Telescope"),
    ),
    "nature_life": (
        ("Q2", "Earth"),
        ("Q525", "Sun"),
        ("Q523", "Star"),
        ("Q4022", "River"),
        ("Q8502", "Mountain"),
        ("Q405", "Moon"),
        ("Q111", "Mars"),
        ("Q318", "Galaxy"),
        ("Q9430", "Ocean"),
        ("Q8072", "Volcano"),
        ("Q35666", "Glacier"),
        ("Q8514", "Desert"),
        ("Q9444", "Rainforest"),
        ("Q11292", "Coral reef"),
        ("Q7377", "Mammal"),
        ("Q5113", "Bird"),
        ("Q25314", "Angiosperms"),
        ("Q430", "Dinosaur"),
        ("Q37813", "Ecosystem"),
        ("Q47041", "Biodiversity"),
    ),
    "places_architecture": (
        ("Q60", "New York City"),
        ("Q84", "London"),
        ("Q85", "Cairo"),
        ("Q90", "Paris"),
        ("Q220", "Rome"),
        ("Q1490", "Tokyo"),
        ("Q5465", "Cape Town"),
        ("Q1489", "Mexico City"),
        ("Q406", "Istanbul"),
        ("Q956", "Beijing"),
        ("Q243", "Eiffel Tower"),
        ("Q10285", "Colosseum"),
        ("Q9141", "Taj Mahal"),
        ("Q12501", "Great Wall of China"),
        ("Q45178", "Sydney Opera House"),
        ("Q48435", "Sagrada Familia"),
        ("Q12495", "Burj Khalifa"),
        ("Q463179", "Fallingwater"),
        ("Q179199", "Guggenheim Museum Bilbao"),
        ("Q2981", "Notre-Dame de Paris"),
    ),
    "art_design": (
        ("Q5582", "Vincent van Gogh"),
        ("Q5588", "Frida Kahlo"),
        ("Q5593", "Pablo Picasso"),
        ("Q12418", "Mona Lisa"),
        ("Q45585", "The Starry Night"),
        ("Q175036", "Guernica"),
        ("Q471379", "The Scream"),
        ("Q185372", "Girl with a Pearl Earring"),
        ("Q25729", "The Persistence of Memory"),
        ("Q296", "Claude Monet"),
        ("Q46408", "Georgia O'Keeffe"),
        ("Q231121", "Yayoi Kusama"),
        ("Q762", "Leonardo da Vinci"),
        ("Q5586", "Hokusai"),
        ("Q5592", "Michelangelo"),
        ("Q5598", "Rembrandt"),
        ("Q5577", "Salvador Dali"),
        ("Q5603", "Andy Warhol"),
        ("Q188740", "Museum of Modern Art"),
        ("Q124354", "Bauhaus"),
    ),
    "literature_language": (
        ("Q42", "Douglas Adams"),
        ("Q692", "William Shakespeare"),
        ("Q41567", "Hamlet"),
        ("Q214371", "The Great Gatsby"),
        ("Q15228", "The Lord of the Rings"),
        ("Q8337", "Harry Potter"),
        ("Q170583", "Pride and Prejudice"),
        ("Q208460", "Nineteen Eighty-Four"),
        ("Q480", "Don Quixote"),
        ("Q35160", "Odyssey"),
        ("Q6691", "Homer"),
        ("Q36322", "Jane Austen"),
        ("Q3335", "George Orwell"),
        ("Q892", "J. R. R. Tolkien"),
        ("Q40909", "Virginia Woolf"),
        ("Q72334", "Toni Morrison"),
        ("Q5878", "Gabriel Garcia Marquez"),
        ("Q1860", "English"),
        ("Q13955", "Arabic"),
        ("Q315", "Language"),
    ),
    "music_performance": (
        ("Q254", "Wolfgang Amadeus Mozart"),
        ("Q1299", "The Beatles"),
        ("Q255", "Ludwig van Beethoven"),
        ("Q1339", "Johann Sebastian Bach"),
        ("Q36153", "Beyonce"),
        ("Q5383", "David Bowie"),
        ("Q174957", "Nina Simone"),
        ("Q93341", "Miles Davis"),
        ("Q104358", "Billie Holiday"),
        ("Q392", "Bob Dylan"),
        ("Q11036", "The Rolling Stones"),
        ("Q26876", "Taylor Swift"),
        ("Q2831", "Michael Jackson"),
        ("Q1744", "Madonna"),
        ("Q125121", "Aretha Franklin"),
        ("Q8341", "Jazz"),
        ("Q11401", "Hip hop music"),
        ("Q1344", "Opera"),
        ("Q41425", "Ballet"),
        ("Q8355", "Violin"),
    ),
    "film_media": (
        ("Q462", "Star Wars"),
        ("Q155653", "Spirited Away"),
        ("Q24815", "Citizen Kane"),
        ("Q47703", "The Godfather"),
        ("Q189540", "Seven Samurai"),
        ("Q61448040", "Parasite"),
        ("Q55400", "Hayao Miyazaki"),
        ("Q8006", "Akira Kurosawa"),
        ("Q11424", "Film"),
        ("Q289", "Television"),
        ("Q11633", "Photography"),
        ("Q7374", "Alfred Hitchcock"),
        ("Q8877", "Steven Spielberg"),
        ("Q8704", "Walt Disney"),
        ("Q132689", "Casablanca"),
        ("Q83495", "The Matrix"),
        ("Q104123", "Pulp Fiction"),
        ("Q11425", "Animation"),
        ("Q19020", "Academy Awards"),
        ("Q41253", "Movie theater"),
    ),
    "sports_games": (
        ("Q19317", "FIFA World Cup"),
        ("Q5389", "Olympic Games"),
        ("Q2736", "Association football"),
        ("Q5372", "Basketball"),
        ("Q847", "Tennis"),
        ("Q718", "Chess"),
        ("Q5369", "Baseball"),
        ("Q5375", "Cricket"),
        ("Q5849", "Rugby union"),
        ("Q1968", "Formula One"),
        ("Q33881", "Tour de France"),
        ("Q32096", "Super Bowl"),
        ("Q41520", "Wimbledon Championships"),
        ("Q155223", "National Basketball Association"),
        ("Q615", "Lionel Messi"),
        ("Q11459", "Serena Williams"),
        ("Q41421", "Michael Jordan"),
        ("Q36107", "Muhammad Ali"),
        ("Q12897", "Pele"),
        ("Q1189", "Usain Bolt"),
    ),
}


def main() -> None:
    catalog = {
        "version": 2,
        "categories": [
            {
                "id": category,
                "anchors": [
                    {
                        "qid": qid,
                        "label": label,
                        "reason": f"Reviewed starter for {category.replace('_', ' ')} connections.",
                    }
                    for qid, label in anchors
                ],
            }
            for category, anchors in SEEDS.items()
        ],
    }
    serialized = json.dumps(catalog, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    CATALOG_PATH.write_text(serialized, encoding="utf-8")
    manifest = {
        "version": 2,
        "catalog": "data/seeds/anchors.v2.json",
        "qid_count": sum(len(anchors) for anchors in SEEDS.values()),
        "category_counts": {category: len(anchors) for category, anchors in SEEDS.items()},
        "sha256": hashlib.sha256(serialized.encode()).hexdigest(),
        "verification": {
            "api_action": "wbgetentities",
            "result": "200 of 200 English labels resolved to unique Wikidata items",
            "verified_at": "2026-07-16",
        },
    }
    MANIFEST_PATH.write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
